steps:
  - label: "🔨 Test"
    command: echo "Try uploading JUnit"
    env:
      BUILDKITE_ANALYTICS_TOKEN: ehRsnV46XFgoyE8SWLPRv2Dz
    plugins:
      - test-collector#v1.10.0:
          files: "results.xml"
          format: "junit"

  - label: "Publish"
    command:
      - echo "Testspace push content"
      - testspace config url munderseth.testspace.com
      - testspace results.xml
    key: push
