steps:
  - label: git-repo
    commands:
      - echo "clone build"
      - git clone https://github.com/munderseth/my.buildkite.git
    key: git

  - label: "Publish"
    commands:
      - echo "Testspace push content"
      - setx CI true
      - testspace config url munderseth.testspace.com
      - testspace results.xml
    key: push
    depends_on: git