steps:
  - label: "Publish"
    commands:
      - echo "Testspace push content"
      - export PATH=$PATH:$HOME/testspace
      - export CI=true
      #- set CI=true
      #- testspace config url munderseth.testspace.com
      #- testspace config
      #- testspace results.xml "#Build %BUILDKITE_BUILD_NUMBER%"
      - testspace results.xml "munderseth.testspace.com/munderseth:my.buildkite/main#Build %BUILDKITE_BUILD_NUMBER%"
    key: push
