steps:
  - label: "One"
    command: echo "Build"
    key: build

  - label: "Two"
    command: echo "Test"
    key: test
    depends_on: build

  - label: "Publish"
    command: |
      echo "Testspace push content"
      testspace config url 45a1dedb94e4d841306f18f11f5591a937fc3884:@munderseth.testspace.com/munderseth:my.buildkite/main
      testspace results.xml
    key: deploy
    depends_on: test