steps:
  - label: "Publish"
    commands:
      - echo "Testspace push content"
      - testspace -v
      #- testspace config url munderseth.testspace.com
      - testspace config
    key: push
