steps:
  - label: git-repo
    commands:
      - echo "git head"
      - git pull
    key: git

  - label: "Publish"
    commands:
      - echo "Testspace push content"
      - testspace config url munderseth.testspace.com
      - testspace results.xml
    key: push
    depends_on: git